/*
 * THE OG / TWITTER CARD'S FILENAME — the ONE place it is written (Story 3.3,
 * code review 2026-08-27).
 *
 * GENERATED BY `scripts/generate-og-card.py`. Edit the card, not this file: the
 * generator rewrites the line below with the hash of the bytes it just wrote.
 *
 * THE HASH IS NOT DECORATION. WhatsApp, Slack, Facebook and X cache an unfurled
 * image per URL for long, uncontrollable periods, so under a stable filename every
 * link already shared would keep the old picture forever. A redesign changes the
 * hash, which changes the URL, which is what makes the new card reachable.
 *
 * WHY A CONSTANT AND NOT FIVE LITERALS. `openGraph` is replaced wholesale by any
 * child that declares it, so the images object genuinely must appear at all five
 * metadata sites — but the URL inside it does not. Importing it is what stops the
 * five copies drifting; before this existed, the export gate asserted the URL's
 * origin and never its value.
 *
 * WHY THE URL AND NOT THE WHOLE IMAGES OBJECT (§D8, and it was checked against the
 * rule rather than the prose). `eslint.config.mjs`'s metadata selector keys on
 * `title|description|default|template|absolute|alt|siteName`. `url` is NOT among
 * them, so moving it here costs nothing — while `alt: t("meta.ogImageAlt")` stays
 * inline at all five sites, inside the only AST scope that rule can reach. Lifting
 * the whole object would take `alt` out of that scope and silently disable AC4.
 */
export const OG_CARD_FILENAME = "og-card-7ac312ef.png";

export const OG_CARD_PATH = `/${OG_CARD_FILENAME}`;
