import type { ReactNode } from "react";

import { compareText } from "@/lib/format";

/*
 * UX-DR12's client-side sort contract, as a PURE module: no React runtime, no
 * DOM, no t(). The only React reference is the `ReactNode` TYPE on
 * `TableColumn.render` — `import type` is erased at compile time and carries no
 * module-graph edge, so this file stays as testable as src/viz/**.
 *
 * It lives in src/lib/ rather than src/viz/ because it is not a visualization
 * model: it is the shared table's decision layer, and it imports @/lib/format,
 * which src/viz/** keeps out by design discipline.
 *
 * EVERYTHING THE SHARED TABLE DECIDES THAT IS NOT A DOM DECISION LIVES HERE.
 * The harness has no jsdom, so a rendered decision cannot be unit-tested at
 * all; both defects Story 2.7's review found were in rendered code and were
 * structurally invisible to a green suite. Pushing the orderings, the cycle and
 * the aria-sort mapping down here is what makes them assertable.
 */

/**
 * One column of a sortable data table — THE CONTRACT (Story 2.11a decision 2).
 *
 * `rows` + `columns` is an API inversion: the caller stops writing `<tr>`/`<td>`
 * and describes its columns instead. Every call site needs more than a field
 * read — an own-goal suffix composing two dictionary keys on a row boolean, a
 * minute cell formatted from a `MinuteStamp`, six cells generated by mapping a
 * frozen code list over a nested record, four columns behind presence gates —
 * so `render` is a closure over `t` and `locale` at the CALL SITE and `sort` is
 * a getter, never a field name.
 */
export interface TableColumn<Row> {
  /** Stable identity. NEVER an index — column sets are dynamic (presence gates). */
  key: string;
  /** Already-resolved head text: t() is called at the CALL SITE, not here. */
  headText: string;
  /** Full term when headText is abbreviated; null otherwise. */
  headTitle: string | null;
  /** Cell body. Closes over t and locale at the call site. */
  render: (row: Row) => ReactNode;
  /**
   * `numeric` right-aligns in type-table-numeric; `clock` is LEFT-aligned
   * tabular-nums (MomentumSection's minute column needs exactly this).
   */
  align: "text" | "numeric" | "clock";
  /** Renders <th scope="row"> instead of <td>. At most one per row. */
  rowHeader?: boolean;
  /**
   * Sort key, INDEPENDENT of render. null-valued rows sort to the array END in
   * BOTH directions. `sort: null` makes the column unsortable.
   *
   * `valueOf` returns the rendered SEMANTIC value, never the raw model field. A
   * `DictionaryKey` column sorts on `t(key)` resolved at the call site — sorting
   * on the raw key would order by "enums.shotOutcome.blocked" and would not
   * re-order under the EN toggle. A clock column sorts on `clockSortValue`,
   * never on the rendered "45+2′" string, which collates after "9′".
   */
  sort:
    | { kind: "number"; valueOf: (row: Row) => number | null }
    | { kind: "text"; valueOf: (row: Row) => string | null }
    | null;
}

export type SortDirection = "ascending" | "descending";

/**
 * The active sort, or `null` for "no column active".
 *
 * THERE IS NO `defaultSort` (decision 5). Every table mounts with `null`, which
 * IS the artifact order (AD-5: "the App may filter, select, and perform
 * user-initiated re-ordering only — canonical/default order always comes from
 * the artifact"). AC 2's "default sort is stated" is discharged by each table's
 * CAPTION, never by a sorted-on-mount column.
 */
export interface SortState {
  columnKey: string;
  direction: SortDirection;
}

/**
 * 0 for a present value, 1 for `null` — the ONE statement of "nulls last",
 * shared by the exported comparators and by `sortRows` so the two can never
 * drift apart.
 */
function nullRank(value: unknown): 0 | 1 {
  return value === null ? 1 : 0;
}

/**
 * Wraps an ascending comparator so `null` ranks after every present value,
 * matching `orderByMinute`'s `left == null ? 1 : -1` (viz/marker-layout.ts).
 */
function nullLast<Value>(
  compareDefined: (a: Value, b: Value) => number
): (a: Value | null, b: Value | null) => number {
  return (a, b) => {
    const rank = nullRank(a) - nullRank(b);
    if (rank !== 0) {
      return rank;
    }
    if (a === null || b === null) {
      return 0;
    }
    return compareDefined(a, b);
  };
}

/**
 * The ONE null-last numeric comparator (decision 3), so no table re-implements
 * it. Ascending; `sortRows` supplies the direction.
 */
export const compareNumberNullLast: (a: number | null, b: number | null) => number =
  nullLast<number>((a, b) => a - b);

/**
 * The null-last text comparator. Goes through `compareText` at its `'es'`
 * DEFAULT (decision 8) — two arguments, which is what UX-DR12 asks for
 * verbatim, and constructs no second collator.
 *
 * Never `localeCompare`, never `<`/`>` on strings: both order every capital
 * before every lowercase, so "Zapata" would precede "álvarez".
 */
export const compareTextNullLast: (a: string | null, b: string | null) => number =
  nullLast<string>((a, b) => compareText(a, b));

/**
 * A clock column's sort value: `minute * 1000 + (stoppageMinute ?? 0)`, or
 * `null` when there is no clock at all.
 *
 * The 1000 factor is not decorative — the corpus prints stoppage values into
 * the twenties, and a smaller scale would let `45+99` overtake minute 46.
 *
 * NULL, NEVER 0, for an absent clock: a `?? 0` here would sort every clock-less
 * row FIRST while `orderByMinute` sorts it last, and would silently claim
 * minute 0 for it. That is the exact defect this story closes in
 * `shot-map-model.ts` (decision 3).
 */
export function clockSortValue(
  minute: number | null | undefined,
  stoppageMinute: number | null | undefined
): number | null {
  if (minute === null || minute === undefined) {
    return null;
  }
  return minute * 1000 + (stoppageMinute ?? 0);
}

/**
 * Rows in display order. `state === null` returns the ARTIFACT ORDER verbatim.
 *
 * STABLE, and stable in both directions: the original index is the tiebreak and
 * is never flipped by the direction, so two rows with equal keys keep their
 * artifact order ascending AND descending. `null` values sort to the END OF THE
 * ARRAY in both directions — descending does not float them to the top.
 *
 * An unknown or unsortable `columnKey` falls back to artifact order rather than
 * throwing: sort state is ephemeral component state and a column set is dynamic
 * (a presence gate can remove the active column between renders).
 */
export function sortRows<Row>(
  rows: readonly Row[],
  columns: readonly TableColumn<Row>[],
  state: SortState | null
): Row[] {
  if (state === null) {
    return [...rows];
  }
  const column = columns.find((candidate) => candidate.key === state.columnKey);
  if (column === undefined || column.sort === null) {
    return [...rows];
  }
  const sign = state.direction === "ascending" ? 1 : -1;
  if (column.sort.kind === "number") {
    return sortByValue(rows, column.sort.valueOf, (a, b) => a - b, sign);
  }
  return sortByValue(rows, column.sort.valueOf, (a, b) => compareText(a, b), sign);
}

function sortByValue<Row, Value>(
  rows: readonly Row[],
  valueOf: (row: Row) => Value | null,
  compareDefined: (a: Value, b: Value) => number,
  sign: number
): Row[] {
  const decorated = rows.map((row, index) => ({ row, index, value: valueOf(row) }));
  decorated.sort((left, right) => {
    const rank = nullRank(left.value) - nullRank(right.value);
    if (rank !== 0) {
      // Unsigned on purpose: nulls belong at the END in BOTH directions.
      return rank;
    }
    if (left.value === null || right.value === null) {
      return left.index - right.index;
    }
    const delta = compareDefined(left.value, right.value);
    // The tiebreak is never signed either — equal rows must not flip.
    return delta !== 0 ? sign * delta : left.index - right.index;
  });
  return decorated.map((entry) => entry.row);
}

/**
 * The cycle: none -> ascending -> descending -> none, where "none" is NO ACTIVE
 * COLUMN and restores artifact order (decision 5). Activating a different
 * column always starts that column ascending rather than inheriting the old
 * direction.
 */
export function nextSortState(current: SortState | null, columnKey: string): SortState | null {
  if (current === null || current.columnKey !== columnKey) {
    return { columnKey, direction: "ascending" };
  }
  if (current.direction === "ascending") {
    return { columnKey, direction: "descending" };
  }
  return null;
}

/**
 * The `aria-sort` value for one column head. In the "none" state EVERY `<th>`
 * reads `"none"` — the third state of the cycle is "no column active", not
 * "column X ascending".
 */
export function ariaSortFor(
  state: SortState | null,
  columnKey: string
): "none" | SortDirection {
  if (state === null || state.columnKey !== columnKey) {
    return "none";
  }
  return state.direction;
}
