import type { ReactNode } from "react";

import { compareText } from "@/lib/format";

/*
 * UX-DR12's client-side sort contract, as a PURE module: no React runtime, no
 * DOM, no t(). The only React reference is the `ReactNode` TYPE on
 * `TableColumn.render` — `import type` is erased at compile time and carries no
 * module-graph edge, so this file stays as testable as src/viz/**.
 *
 * It lives in src/lib/ rather than src/viz/ because it is not a visualization
 * model: it is the shared table's decision layer, and it imports @/lib/format,
 * which src/viz/** keeps out by design discipline.
 *
 * EVERYTHING THE SHARED TABLE DECIDES THAT IS NOT A DOM DECISION LIVES HERE.
 * The harness has no jsdom, so a rendered decision cannot be unit-tested at
 * all; both defects Story 2.7's review found were in rendered code and were
 * structurally invisible to a green suite. Pushing the orderings, the cycle and
 * the aria-sort mapping down here is what makes them assertable.
 */

/**
 * One column of a sortable data table — THE CONTRACT (Story 2.11a decision 2).
 *
 * `rows` + `columns` is an API inversion: the caller stops writing `<tr>`/`<td>`
 * and describes its columns instead. Every call site needs more than a field
 * read — an own-goal suffix composing two dictionary keys on a row boolean, a
 * minute cell formatted from a `MinuteStamp`, six cells generated by mapping a
 * frozen code list over a nested record, four columns behind presence gates —
 * so `render` is a closure over `t` and `locale` at the CALL SITE and `sort` is
 * a getter, never a field name.
 */
export interface TableColumn<Row> {
  /** Stable identity. NEVER an index — column sets are dynamic (presence gates). */
  key: string;
  /** Already-resolved head text: t() is called at the CALL SITE, not here. */
  headText: string;
  /** Full term when headText is abbreviated; null otherwise. */
  headTitle: string | null;
  /** Cell body. Closes over t and locale at the call site. */
  render: (row: Row) => ReactNode;
  /**
   * `numeric` right-aligns in type-table-numeric; `clock` is LEFT-aligned
   * tabular-nums (MomentumSection's minute column needs exactly this).
   */
  align: "text" | "numeric" | "clock";
  /** Renders <th scope="row"> instead of <td>. At most one per row. */
  rowHeader?: boolean;
  /*
   * PRESENTATION ONLY (Story 2.11b). Neither field reaches `sortRows` — they
   * exist because a STICKY COLUMN RUN cannot be expressed any other way: each
   * column in the run needs its own explicit `left` offset and an opaque fill,
   * and a class string cannot be computed from the column list. Both are
   * `undefined` at all 26 pre-2.11b call sites, and `cn()` makes an undefined
   * extra a no-op, so the default rendering is byte-identical.
   */
  /** Extra classes for this column's <th> AND <td> — width, offset, fill. */
  cellClass?: string;
  /** Extra classes for this column's <thead> cell only — the z-index ladder. */
  headClass?: string;
  /**
   * Sort key, INDEPENDENT of render. null-valued rows sort to the array END in
   * BOTH directions. `sort: null` makes the column unsortable.
   *
   * `valueOf` returns the rendered SEMANTIC value, never the raw model field. A
   * `DictionaryKey` column sorts on `t(key)` resolved at the call site — sorting
   * on the raw key would order by "enums.shotOutcome.blocked" and would not
   * re-order under the EN toggle. A clock column sorts on `clockSortValue`,
   * never on the rendered "45+2′" string, which collates after "9′".
   */
  sort:
    | { kind: "number"; valueOf: (row: Row) => number | null }
    | { kind: "text"; valueOf: (row: Row) => string | null }
    | null;
}

export type SortDirection = "ascending" | "descending";

/**
 * The active sort, or `null` for "no column active".
 *
 * THERE IS NO `defaultSort` (decision 5). Every table mounts with `null`, which
 * IS the artifact order (AD-5: "the App may filter, select, and perform
 * user-initiated re-ordering only — canonical/default order always comes from
 * the artifact"). AC 2's "default sort is stated" is discharged by each table's
 * CAPTION, never by a sorted-on-mount column.
 */
export interface SortState {
  columnKey: string;
  direction: SortDirection;
}

/**
 * "Absent" for ranking purposes.
 *
 * `undefined` COUNTS AS ABSENT even though the `valueOf` signatures return
 * `Value | null`. A getter reading an index off a `Record<Code, number>` is
 * typed `number` whether or not the key is present, so a record built as
 * `{} as Record<…>` and filled from a list can hand us `undefined` with no type
 * error. Ranking that as PRESENT would send it into `a - b` -> `NaN`, and
 * `Array.prototype.sort` coerces a `NaN` comparator result to `+0` — silently
 * discarding the index tiebreak and the stability guarantee with it.
 * `clockSortValue` already normalizes `undefined`; this makes the whole module
 * agree with it. (Review patch, Story 2.11a.)
 */
function isAbsent(value: unknown): boolean {
  return value === null || value === undefined;
}

/** 0 for a present value, 1 for an absent one — the ONE statement of "nulls last". */
function nullRank(value: unknown): 0 | 1 {
  return isAbsent(value) ? 1 : 0;
}

/**
 * Wraps an ascending comparator so an absent value ranks after every present
 * one, matching `orderByMinute`'s `left == null ? 1 : -1`
 * (viz/marker-layout.ts).
 */
function nullLast<Value>(
  compareDefined: (a: Value, b: Value) => number
): (a: Value | null, b: Value | null) => number {
  return (a, b) => {
    const rank = nullRank(a) - nullRank(b);
    if (rank !== 0) {
      return rank;
    }
    if (isAbsent(a) || isAbsent(b)) {
      return 0;
    }
    return compareDefined(a as Value, b as Value);
  };
}

/**
 * The ONE null-last numeric comparator (decision 3), so no table re-implements
 * it. Ascending; `sortRows` supplies the direction.
 */
export const compareNumberNullLast: (a: number | null, b: number | null) => number =
  nullLast<number>((a, b) => a - b);

/**
 * The null-last text comparator. Goes through `compareText` at its `'es'`
 * DEFAULT (decision 8) — two arguments, which is what UX-DR12 asks for
 * verbatim, and constructs no second collator.
 *
 * Never `localeCompare`, never `<`/`>` on strings: both order every capital
 * before every lowercase, so "Zapata" would precede "álvarez".
 */
export const compareTextNullLast: (a: string | null, b: string | null) => number =
  nullLast<string>((a, b) => compareText(a, b));

/**
 * A clock column's sort value: `minute * 1000 + (stoppageMinute ?? 0)`, or
 * `null` when there is no clock at all.
 *
 * The 1000 factor is not decorative — the corpus prints stoppage values into
 * the twenties, and a smaller scale would let `45+99` overtake minute 46.
 *
 * NULL, NEVER 0, for an absent clock: a `?? 0` here would sort every clock-less
 * row FIRST while `orderByMinute` sorts it last, and would silently claim
 * minute 0 for it. That is the exact defect this story closes in
 * `shot-map-model.ts` (decision 3).
 */
export function clockSortValue(
  minute: number | null | undefined,
  stoppageMinute: number | null | undefined
): number | null {
  if (minute === null || minute === undefined) {
    return null;
  }
  return minute * 1000 + (stoppageMinute ?? 0);
}

/**
 * Rows in display order. `state === null` returns the ARTIFACT ORDER verbatim.
 *
 * STABLE, and stable in both directions: the original index is the tiebreak and
 * is never flipped by the direction, so two rows with equal keys keep their
 * artifact order ascending AND descending. `null` values sort to the END OF THE
 * ARRAY in both directions — descending does not float them to the top.
 *
 * An unknown or unsortable `columnKey` falls back to artifact order rather than
 * throwing: sort state is ephemeral component state and a column set is dynamic
 * (a presence gate can remove the active column between renders).
 */
export function sortRows<Row>(
  rows: readonly Row[],
  columns: readonly TableColumn<Row>[],
  state: SortState | null
): Row[] {
  if (state === null) {
    return [...rows];
  }
  const column = columns.find((candidate) => candidate.key === state.columnKey);
  if (column === undefined || column.sort === null) {
    return [...rows];
  }
  const sign = state.direction === "ascending" ? 1 : -1;
  if (column.sort.kind === "number") {
    return sortByValue(rows, column.sort.valueOf, compareNumberNullLast, sign);
  }
  return sortByValue(rows, column.sort.valueOf, compareTextNullLast, sign);
}

/**
 * `compare` is one of the EXPORTED null-last comparators above — never a second
 * inline restatement of the ordering.
 *
 * That indirection is the point (review patch, Story 2.11a): an earlier draft
 * re-derived null-last here, so `compareNumberNullLast` / `compareTextNullLast`
 * and their assertions could have kept passing while the shipped table diverged
 * from them. Now the tested comparators ARE the shipped path, and this function
 * adds only the two things a comparator cannot know: the direction, and the
 * stability tiebreak.
 */
function sortByValue<Row, Value>(
  rows: readonly Row[],
  valueOf: (row: Row) => Value | null,
  compare: (a: Value | null, b: Value | null) => number,
  sign: number
): Row[] {
  const decorated = rows.map((row, index) => ({ row, index, value: valueOf(row) }));
  decorated.sort((left, right) => {
    const delta = compare(left.value, right.value);
    if (delta === 0) {
      // The tiebreak is never signed — equal rows must not flip on reversal.
      return left.index - right.index;
    }
    if (isAbsent(left.value) || isAbsent(right.value)) {
      /*
       * Unsigned on purpose: an absent value belongs at the END OF THE ARRAY in
       * BOTH directions, so descending must not float the nulls to the top.
       * `compare` has already ranked them last; signing that would undo it.
       */
      return delta;
    }
    return sign * delta;
  });
  return decorated.map((entry) => entry.row);
}

/**
 * The cycle: none -> ascending -> descending -> none, where "none" is NO ACTIVE
 * COLUMN and restores artifact order (decision 5). Activating a different
 * column always starts that column ascending rather than inheriting the old
 * direction.
 */
export function nextSortState(current: SortState | null, columnKey: string): SortState | null {
  if (current === null || current.columnKey !== columnKey) {
    return { columnKey, direction: "ascending" };
  }
  if (current.direction === "ascending") {
    return { columnKey, direction: "descending" };
  }
  return null;
}

/*
 * ---------------- THE POLITE ANNOUNCEMENT (Story 2.12 amendment) -------------
 *
 * These four consts and `composeSortAnnouncement` were `DataTable`'s private
 * module scope until Story 2.12. They moved here for one reason: the Hub's
 * `<md` sort menu (AC 4) drives the SAME sort state from OUTSIDE the table, so
 * without a shared composer there would be two restatements of one announcement
 * — and the announcement is the only feedback a screen-reader user gets that a
 * sort happened at all.
 *
 * The strings are byte-identical to what `DataTable` emitted before the move.
 */

/** Separates the clauses of the sorted-by announcement. */
const CLAUSE_SEPARATOR = ", ";
const PERIOD = ".";
const SPACE = " ";
/** Separates a table's own name from the sort clause (Story 2.11b). */
const NAME_SEPARATOR = ": ";

/** Already-resolved announcement fragments, supplied by the call site's t(). */
export interface SortAnnouncementLabels {
  sortedBy: string;
  ascending: string;
  descending: string;
  cleared: string;
}

/**
 * The polite announcement for a sort transition.
 *
 * `headText` is the ACTIVE column's resolved head; it is unread when `state` is
 * null, because the cycle's third state names no column — none is active.
 *
 * `tableName` prefixes BOTH states, the cleared one included: "the table's
 * original order was restored" is exactly as ambiguous across twenty-odd tables
 * as the sorted form, and the Hub renders THIRTY on one route (12 group
 * standings + 12 group results + up to 6 knockout stages).
 */
export function composeSortAnnouncement(input: {
  state: SortState | null;
  headText: string;
  labels: SortAnnouncementLabels;
  tableName?: string;
}): string {
  const { state, headText, labels, tableName } = input;
  const clause =
    state === null
      ? labels.cleared
      : `${labels.sortedBy}${SPACE}${headText}${CLAUSE_SEPARATOR}${
          state.direction === "ascending" ? labels.ascending : labels.descending
        }${PERIOD}`;
  return tableName === undefined ? clause : `${tableName}${NAME_SEPARATOR}${clause}`;
}

/*
 * Wraps the FULL TERM behind an abbreviated head (Story 2.13, UX-DR17/UX-DR19).
 * Module consts rather than literals because `aria-label` is one of the sixteen
 * gated prop names and the i18n gate fires on template literals AND on the
 * operands of concatenation inside them.
 */
const TITLE_OPEN = " (";
const TITLE_CLOSE = ")";

/**
 * A column head's accessible name, carrying the FULL TERM behind an
 * abbreviation. `optionalPrefix` is the sort action on a sortable head and
 * empty on an unsortable one.
 *
 * VISIBLE TEXT FIRST, ALWAYS, and the full term APPENDED in parentheses —
 * never substituted. Swapping `headText` for `headTitle` would set the name to
 * "Ordenar por Velocidad máxima" over visible text reading "Vel. máx.", so the
 * visible label would no longer be contained in the accessible name: a WCAG
 * 2.5.3 Label in Name failure.
 *
 * THE SUPPRESSION TEST IS CONTAINMENT, NOT BYTE-EQUALITY. A caller composes the
 * UNIT into `headText` (ruling 6 puts it head-side) while `headTitle` stays the
 * bare term, so a byte-equality guard never fires on a metric carrying a unit
 * and EN shipped "Sort by Top speed (km/h) (Top speed)" — the exact outcome the
 * guard existed to prevent, and a regression of the Expert Layer's already
 * shipped topSpeed head. Found at the Story 2.13 code review.
 *
 * IT LIVES HERE, not inside `DataTable`, so it can be TESTED. As a closure in a
 * "use client" component it was unreachable from the node-environment suite,
 * and the test that claimed to pin it asserted a hand-built template literal
 * against itself — green even if the function were deleted. Same move, and same
 * reason, as `composeSortAnnouncement` above.
 */
export function composeHeadAccessibleName(
  optionalPrefix: string,
  headText: string,
  headTitle: string | null
): string {
  const base = optionalPrefix === "" ? headText : `${optionalPrefix}${SPACE}${headText}`;
  if (headTitle === null || headText.includes(headTitle)) {
    return base;
  }
  return `${base}${TITLE_OPEN}${headTitle}${TITLE_CLOSE}`;
}

/**
 * The `aria-sort` value for one column head. In the "none" state EVERY `<th>`
 * reads `"none"` — the third state of the cycle is "no column active", not
 * "column X ascending".
 */
export function ariaSortFor(
  state: SortState | null,
  columnKey: string
): "none" | SortDirection {
  if (state === null || state.columnKey !== columnKey) {
    return "none";
  }
  return state.direction;
}
